// Generated by Selenium IDE
package edu.pitt.cs;
import static org.hamcrest.MatcherAssert.assertThat;
import java.time.Duration;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import org.junit.FixMethodOrder;
import org.junit.runners.MethodSorters;
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class D3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    ChromeOptions options = new ChromeOptions();
    options.addArguments("--headless");
    driver = new ChromeDriver(options);
    //driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(30));
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tEST1LINKS() {
    driver.get("http://localhost:8080/");
    {
      List<WebElement> elements = driver.findElements(By.xpath("//a[contains(@href, \'/reset\')]"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tEST2RESET() {
    driver.get("http://localhost:8080/");
    js.executeScript("document.cookie = \"1=true\";document.cookie = \"2=true\";document.cookie = \"3=true\";");
    driver.findElement(By.linkText("Reset")).click();
    vars.put("id1", driver.findElement(By.xpath("//div/ul/li[1]")).getText());
    assertEquals(vars.get("id1").toString(), "ID 1. Jennyanydots");
    vars.put("Id2", driver.findElement(By.xpath("//div/ul/li[2]")).getText());
    assertEquals(vars.get("Id2").toString(), "ID 2. Old Deuteronomy");
    vars.put("Id3", driver.findElement(By.xpath("//div/ul/li[3]")).getText());
    assertEquals(vars.get("Id3").toString(), "ID 3. Mistoffelees");
  }
  @Test
  public void tEST3CATALOG() {
    driver.get("http://localhost:8080/");
    driver.findElement(By.linkText("Catalog")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//li[2]/img"));
      assert(elements.size() > 0);
    }
    {
      WebElement element = driver.findElement(By.xpath("//li[2]/img"));
      String attribute = element.getAttribute("src");
      vars.put("ImgSrc", attribute);
    }
    assertEquals(vars.get("ImgSrc").toString(), "http://localhost:8080/images/cat2.jpg");
  }
  @Test
  public void tEST4LISTING() {
    driver.get("http://localhost:8080/");
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div/ul/li[3]"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div/ul/li[4]"));
      assert(elements.size() == 0);
    }
    vars.put("id3", driver.findElement(By.xpath("//div/ul/li[3]")).getText());
    assertEquals(vars.get("id3").toString(), "ID 3. Mistoffelees");
  }
  @Test
  public void tEST5RENTACAT() {
    driver.get("http://localhost:8080/");
    driver.findElement(By.linkText("Rent-A-Cat")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[contains(.,\'Rent\')]"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[contains(.,\'Return\')]"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tEST6RENT() {
    driver.get("http://localhost:8080/");
    driver.findElement(By.linkText("Rent-A-Cat")).click();
    driver.findElement(By.xpath("//input[@id=\'rentID\']")).click();
    driver.findElement(By.xpath("//input[@id=\'rentID\']")).sendKeys("1");
    driver.findElement(By.xpath("//button[contains(.,\'Rent\')]")).click();
    vars.put("1", driver.findElement(By.xpath("//div/ul/li[1]")).getText());
    assertEquals(vars.get("1").toString(), "Rented out");
    vars.put("2", driver.findElement(By.xpath("//div/ul/li[2]")).getText());
    assertEquals(vars.get("2").toString(), "ID 2. Old Deuteronomy");
    vars.put("3", driver.findElement(By.xpath("//div/ul/li[3]")).getText());
    assertEquals(vars.get("3").toString(), "ID 3. Mistoffelees");
    vars.put("result", driver.findElement(By.id("rentResult")).getText());
    assertEquals(vars.get("result").toString(), "Success!");
  }
  @Test
  public void tEST8FEEDACAT() {
    driver.get("http://localhost:8080/");
    driver.findElement(By.xpath("//a[contains(text(),\'Feed-A-Cat\')]")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[contains(.,\'Feed\')]"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tEST7RETURN() {
    driver.get("http://localhost:8080/");
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=true\";document.cookie = \"3=false\";");
    driver.findElement(By.linkText("Rent-A-Cat")).click();
    driver.findElement(By.xpath("//input[@id=\'returnID\']")).click();
    driver.findElement(By.xpath("//input[@id=\'returnID\']")).sendKeys("2");
    driver.findElement(By.xpath("//button[contains(.,\'Return\')]")).click();
    vars.put("1", driver.findElement(By.xpath("//div/ul/li[1]")).getText());
    assertEquals(vars.get("1").toString(), "ID 1. Jennyanydots");
    vars.put("2", driver.findElement(By.xpath("//div/ul/li[2]")).getText());
    assertEquals(vars.get("2").toString(), "ID 2. Old Deuteronomy");
    vars.put("3", driver.findElement(By.xpath("//div/ul/li[3]")).getText());
    assertEquals(vars.get("3").toString(), "ID 3. Mistoffelees");
    vars.put("result", driver.findElement(By.xpath("//div[@id=\'returnResult\']")).getText());
    assertEquals(vars.get("result").toString(), "Success!");
  }
  @Test
  public void tEST9FEED() {
    driver.get("http://localhost:8080/");
    driver.findElement(By.xpath("//a[contains(text(),\'Feed-A-Cat\')]")).click();
    driver.findElement(By.xpath("//input[@id=\'catnips\']")).click();
    driver.findElement(By.xpath("//input[@id=\'catnips\']")).sendKeys("6");
    driver.findElement(By.xpath("//button[contains(.,\'Feed\')]")).click();
    vars.put("result", driver.findElement(By.xpath("//div[@id=\'feedResult\']")).getText());
    assertEquals(vars.get("result").toString(), "Nom, nom, nom.");
  }
  @Test
  public void tEST10GREETACAT() {
    driver.get("http://localhost:8080/");
    driver.findElement(By.xpath("//a[contains(text(),\'Greet-A-Cat\')]")).click();
    vars.put("greeting", driver.findElement(By.xpath("//div[@id=\'greeting\']/h4")).getText());
    assertEquals(vars.get("greeting").toString(), "Meow!Meow!Meow!");
  }
  @Test
  public void tEST11GREETACATWITHNAME() {
    driver.get("http://localhost:8080/greet-a-cat/Jennyanydots");
    vars.put("greeting", driver.findElement(By.xpath("//div[@id=\'greeting\']/h4")).getText());
    assertEquals(vars.get("greeting").toString(), "Meow! from Jennyanydots.");
  }
 
  
 
}
